### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by bwised** [paveldudka/JacocoEverywhere#12]
When I use this plugin (version 0.2.1), I get a StackOverflowError.  The stack trace is pretty long, but it repeats, so I'll copy the repeating snippet here:

```
Caused by: java.lang.StackOverflowError
    at org.jacoco.agent.rt.internal_b0d6a23.core.data.ExecutionDataStore.$jacocoInit(ExecutionDataStore.java)
    at org.jacoco.agent.rt.internal_b0d6a23.core.data.ExecutionDataStore.get(ExecutionDataStore.java)
    at org.jacoco.agent.rt.internal_b0d6a23.core.runtime.RuntimeData.getExecutionData(RuntimeData.java:120)
    at org.jacoco.agent.rt.internal_b0d6a23.core.runtime.RuntimeData.getProbes(RuntimeData.java:148)
    at org.jacoco.agent.rt.internal_b0d6a23.core.runtime.RuntimeData.equals(RuntimeData.java:162)
    at org.jacoco.agent.rt.internal_b0d6a23.core.data.ExecutionData.$jacocoInit(ExecutionData.java)
    at org.jacoco.agent.rt.internal_b0d6a23.core.data.ExecutionData.<init>(ExecutionData.java)
    at org.jacoco.agent.rt.internal_b0d6a23.core.data.ExecutionDataStore.get(ExecutionDataStore.java:132)
*repeats*
```

If I comment out `apply plugin: 'jacoco-everywhere'` from my gradle file, I can run my tests normally.

**Comment by paveldudka** [comment]
Seems similar to #9 

Is there any chance you also have `jacoco-plugin` applied somewhere in your project?
